[project]
name = "csv-visualizer"
version = "0.1.0"
description = "CSV candlestick visualization tool"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.0.3",
    "plotly>=5.21.0",
    "kaleido>=0.2.1",
] 